### PR TITLE
Migration to 2024 - 1

### PR DESCRIPTION
**Pull request by Hen-Dricks**
We are migrating this tool to support 2024 stats

### CODE REVIEW

**Comment by navindu-sachintha** [comment]
Is this gonna be deployed?

**Comment by ragnarok22** [comment]
I'm excited to see this on live!

**Comment by jis3r** [comment]
@JonnyBurger are the changes sufficient and if so, can we merge it?

**Comment by JaySabva** [comment]
Can someone deploy this?

**Comment by kunkka19xx** [comment]
Looking forward to the merge. 
Today is Dec-13th 😸😸

**Comment by odilson-dev** [comment]
When will this branch branch be merged, we're already on 15th December, I'm excited to see what we've done!

**Comment by JonnyBurger** [comment]
I'll work on this today.

**Comment by JaySabva** [comment]
> I'll work on this today.

It's happening 🔥

**Comment by ragnarok22** [comment]
Go go go! We devs are so silly 🤣 but we love this stuff. Thank u ❤️

**Review by JaySabva — APPROVED** [review]

**Comment by hoc081098** [comment]
Thanks 👍

**Comment by JonnyBurger** [comment]
Planning to ship this later today!

**Comment by ahmedsaed** [comment]
Amazing, thanks a lot for the great work.

~I see the PR being merged but is it deployed yet? Because I still get the 2023 version.~

~If it's already deployed, how do I make it use the 2024 stats?~

Edit: it's working now. But download option is disabled because of an error

**Comment by EmpiteLeo** [comment]
it  working and in 2024 but cant download ```Function not found: arn:aws:lambda:eu-central-1:698512585966:function:remotion-render-4-0-240-mem1200mb-disk10240mb-120sec```

**Comment by ragnarok22** [comment]
Good work!

**Comment by JonnyBurger** [comment]
It should all be working now!
I'll keep improving in the meanwhile.

**Pull request merged**
